### ISSUE TITLE
how does visualization work? all i see are .h5ad files listed as output

### ISSUE THREAD

**Issue by mohammedkhalfan** [genepattern/ScanpyPreprocess#12]
Hello,

I was able to run ScanpyUtilities in GPN very easily, but how do I visualize the results? The job finished but all i see are the .h5ad files listed as outputs. Are there any visualizations built into ScanpyUtilities? Thank you. 
![image](https://user-images.githubusercontent.com/11298184/66169729-5f57d380-e60f-11e9-953e-0a376bdafff0.png)

**Comment by bahill** [comment]
Hi Mohammed,

We'll follow up on this question in your thread on our forum. 

https://groups.google.com/forum/#!topic/genepattern-help/1zTjbVnNYpY

Thank you for contacting us,
Barbara
